os: osx
language: objective-c
osx_image: xcode9.1
podfile: ManUpDemo/Podfile

script:
- xcodebuild -workspace ManUpDemo/ManUpDemo.xcworkspace -scheme ManUpDemo -destination "platform=iOS Simulator,name=iPhone SE" test | xcpretty;
